### ISSUE TITLE
Difference in results between exported model and Quick Test

### ISSUE THREAD

**Issue by MAHashmi** [Azure-Samples/cognitive-services-android-customvision-sample#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> The classifications results (class & confidence) from exported model and "Custom Vision portal's Quick Test" feature differ a lot. Same image produced different results from both methods. The only difference (IMO) is that of subtraction of mean RGB values.

### Any log messages given by the failure
>No

### Expected/desired behavior
>Both methods should provide similar classifications

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>latest

### Mention any other details that might be useful
In the project ReadMe it is mentioned that the mean RGB values for General (compact) domain are (123,117,104) whereas in the actual MSCognitiveServicesClassifier these values are set to be (124, 117, 105). Which one is correct for domain General (compact)?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ksujanpaul** [comment]
MAHsami did you check that in your android device. is it working?

**Comment by MAHashmi** [comment]
Yes, apparently they have updated the service. Now it expects the RGB values to be zero in all cases.

**Comment by bhylak** [comment]
can you explain?

**Comment by shonohs** [comment]
The latest sample code detects the model version automatically, so user doesn't have to take care of this issue.

Seeing slightly different results on this app is expected since this app is using different image preprocessing algorithms. Usually adding more training images can mitigate the difference.

**Comment by bhylak** [comment]
We are seeing this problem simply using the provided python code. Accuracy seen in quick test is around 80% where accuracy through python is 40-30% for the same test data.
