### ISSUE TITLE
Do the RGB mean values depend on the generated model file?

### ISSUE THREAD

**Issue by raymondkpwong** [Azure-Samples/cognitive-services-android-customvision-sample#2]
We've got an issue that the generated model.pb cannot classify an image with the same prediction values as we found using the Custom Vision prediction URL.  When we dig into the codes, we found these RGB mean values.  We are wondering whether these mean values should be adjusted depending on the generated model file or they are meant to be constant for all models exported from Custom Vision.

https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/6f00e328835b7ec56993093d53507cf373045b82/app/src/main/java/demo/tensorflow/org/customvision_sample/MSCognitiveServicesClassifier.java#L45
https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/6f00e328835b7ec56993093d53507cf373045b82/app/src/main/java/demo/tensorflow/org/customvision_sample/MSCognitiveServicesClassifier.java#L46
https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/6f00e328835b7ec56993093d53507cf373045b82/app/src/main/java/demo/tensorflow/org/customvision_sample/MSCognitiveServicesClassifier.java#L47

**Comment by amin-b** [comment]
@raymondkpwong if you are using "General (compact)" or "Retail (compact)" domains, mean values do not need to be adjusted. 
(for "Landmark (compact)" domain mean values for all channels are zero).

could you clarify the issue a little bit more, by "same prediction values" do you mean the image is recognized but with different probabilities or the image is not recognized at all?

also please share the probabilities you get from prediction URL and the values in 'outputs' array in MSCognitiveServicesClassifier.java _classifyImage_ method (around line 110)?

how about image resize/scaling? are you using phone's camera as image input source?
have you made any changes to the sample code?

**Comment by raymondkpwong** [comment]
@amin-b We are using Retail (compact) domain for this.  We actually used the current TensorFlow python library (not this Android master branch) and label_image.py to do this.  We slightly modified label_image.py so that the mean values [124, 117, 105], input_layer "Placeholder", output_layer "loss" and resizing to 227x227 follow this Android sample program.

Python label_image.py result - Top 2 are women and maternity.
```
women 0.859393
maternity 0.382915
top 0.012015
dress 0.00859097
men 0.00320171
shorts 0.00270259
trousers 0.000467964
lingerie 0.000402406
tshirt 0.000172656
cap 7.37267e-07
socks 5.33544e-08
```

Quick test result in CustomVision.ai - Top 2 are women and top.
![image](https://user-images.githubusercontent.com/12294657/34549707-bc00a352-f145-11e7-99e8-6507c174055c.png)

Results are different.

We verified that we used the same project, iteration and test image.  We suppose the Java and Python versions of TF should give the same or similar prediction results.

**Comment by amin-b** [comment]
@raymondkpwong that's right, Java and Python will work the same,
How are you doing the image scaling/cropping?
That should be done the same way as Android sample.

**Comment by raymondkpwong** [comment]
We use this label_image.py from TF.  The line uses the function `tf.image.resize_bilinear` to resize using bilinear.  

https://github.com/tensorflow/tensorflow/blob/6db014b44863bab616f026beab461fd646fcb505/tensorflow/examples/label_image/label_image.py#L55

It looks different in the way as Android one does.  But the [test image](https://media.kohlsimg.com/is/image/kohls/3030051_Black?wid=350&hei=350&op_sharpen=1) is a square image of 350x350.  So I assume the quality would be the same.

**Comment by amin-b** [comment]
@raymondkpwong 
you can just simply resize the image to 227x227 and try it out,

also, are you converting the RGB image to BGR? the model expects a BGR input and as you can see in this Android sample we're [converting it to BGR](https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/6f00e328835b7ec56993093d53507cf373045b82/app/src/main/java/demo/tensorflow/org/customvision_sample/MSCognitiveServicesClassifier.java#L98) before feeding it to TF.

**Comment by amin-b** [comment]
@raymondkpwong any luck?
if there anything specific we can help you with your code?

**Comment by raymondkpwong** [comment]
Still no luck.  We already resized to 227x227.  Tried different options such as reversing RGB and reversing subtraction.

```
normalized = tf.divide(tf.subtract(resized, [105, 117, 124]), [input_std])
women 0.47631
maternity 0.444038
top 0.00863412
men 0.00639937
dress 0.00205008
shorts 0.00197873
trousers 0.000468617
lingerie 6.93435e-05
tshirt 5.94398e-05
cap 8.39072e-07
socks 1.2852e-07
```
```
normalized = tf.divide(tf.subtract(resized, [124, 117, 105]), [input_std])
women 0.859393
maternity 0.382914
top 0.012015
dress 0.00859098
men 0.00320171
shorts 0.0027026
trousers 0.000467964
lingerie 0.000402406
tshirt 0.000172655
cap 7.37269e-07
socks 5.33544e-08
```
```
normalized = tf.divide(tf.subtract(tf.reverse(resized, axis=[-1]), [105, 117, 124]), [input_std])
women 0.954215
maternity 0.577251
dress 0.108349
top 0.0522353
men 0.0103804
trousers 0.00523622
shorts 0.00512224
lingerie 0.00199977
tshirt 0.000111601
cap 5.67962e-06
socks 7.00269e-07
```
```
normalized = tf.divide(tf.subtract(tf.reverse(resized, axis=[-1]), [124, 117, 105]), [input_std])
women 0.97865
maternity 0.534343
dress 0.151853
top 0.0930136
shorts 0.0118261
men 0.0106445
lingerie 0.00782197
trousers 0.00359985
tshirt 0.000304643
cap 1.19202e-05
socks 5.84404e-07
```
All ranks women and maternity as top 2 predictions.  I am wondering if the Android TF output from Custom Vision is correct or not.  It looks like the model we exported is not the same as the model we used in the Custom Vision Prediction API.  Any idea?

**Comment by raymondkpwong** [comment]
Some intermediate images are attached for study.

Original image
![image](https://user-images.githubusercontent.com/12294657/34767433-08cbbcd4-f633-11e7-9fea-e46156d3f763.png)

After RGB to BGR
![image](https://user-images.githubusercontent.com/12294657/34767456-1b28bac6-f633-11e7-9536-9fab7e9020bf.png)

After subtraction of [105, 117, 124]
![image](https://user-images.githubusercontent.com/12294657/34767537-521edefc-f633-11e7-89f5-a997831f31bd.png)

**Comment by amin-b** [comment]
@raymondkpwong would you be able to share your TF model and original image here?

**Comment by amin-b** [comment]
No follow-up/response. Closed.

**Comment by bhylak** [comment]
Also experiencing this same problem.
