### ISSUE TITLE
Tensorflow model configuration for General (compact) domain and Object detection

### ISSUE THREAD

**Issue by petar-marinov** [Azure-Samples/cognitive-services-android-customvision-sample#21]
Hello, we are using a project with General (compact) domain and it is for Object detection. The sample java code in the samples is a bit outdated and it is only for object classification. We are exporting the model to Tensorflow.

Would you please share how we could find needed input and output names for object detection as well as detection bounding boxes and detected names.

We have a working sample with different model but it uses image_tensor as input name and detection_scores, detection_boxes and detection_classes as output. 

We managed to find that in the exported model from Customvision.ai the input name is Placeholder but we are unable to find needed configuration for the outputs.

Thank you very much in advance!

**Comment by sachin-ranka** [comment]
According to [MSConitiveServicesClassifier.java#L50](https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/master/app/src/main/java/demo/tensorflow/org/customvision_sample/MSCognitiveServicesClassifier.java#L50) output is ```loss```, but import to tensorboard and inspect the pb file. Ref. [this link](https://medium.com/@daj/how-to-inspect-a-pre-trained-tensorflow-model-5fd2ee79ced0#f160) to import to tensorboard.
