### ISSUE TITLE
Needs documentation to be updated which contains the model file.

### ISSUE THREAD

**Issue by asishsinha** [Azure-Samples/cognitive-services-android-customvision-sample#30]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>The sample works only for fruits, but while I try to use my model and dropping the files in Assets folder as mentioned here [README.md](https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/master/image_classification/README.md), it does not work because the sample is hard coded to use the model in "fruits-tflite" folder instead of the Assets folder.

Please update the documentation and make aware of this target folder or update the Line 49 of [MSCognitiveServicesCustomVisionClassifier.java](https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/master/image_classification/app/src/main/java/demo/tensorflow/org/customvision_sample/MSCognitiveServicesCustomVisionClassifier.java)

        // Specify the folder that contains the model file and its manifest file
        ImageClassifier.Configuration config = ImageClassifier.ConfigurationBuilder()
                .setModelFile("fruits-tflite/cvexport.manifest").build();

### Any log messages given by the failure
> NA

### Expected/desired behavior
> to work when custom TensorFlow Lite model is dropped in the Assets Folder

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> NA

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kojiwhub** [comment]
Thank you for reporting the issue.  We have updated the document to have correct path to put model files.
