### ISSUE TITLE
cognitive-services-android-customvision-sample/aars/inference-tensorflow-lite-libcpp-1.0.0.aar does not support 64bit

### ISSUE THREAD

**Issue by runfar** [Azure-Samples/cognitive-services-android-customvision-sample#31]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

cognitive-services-android-customvision-sample/aars/inference-**tensorflow-lite-libcpp-1.0.0.aar**  does not support 64bit.
How can I get **inference-tensorflow-lite-libcpp-1.0.0.aar** for 64bit?

Thanks.

### Minimal steps to reproduce
>
  

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Pilzcat** [comment]
I am also actively looking for this. It is impossible to publish an app to Google Play Store now with the current 32-bit only library.
This is highly needed please.

**Comment by amjad-twalo** [comment]
I added newly generated AAR files that support x64 architecture

**Comment by kojiwhub** [comment]
thank you for reproing issue and being patient.  we have made a change to address the issue.  let us close now.
