### ISSUE TITLE
Camera issue 

### ISSUE THREAD

**Issue by AlbertoMocchi** [Azure-Samples/cognitive-services-android-customvision-sample#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I've just downloaded the sample, and all the necessary API; Built the sample and ran it.

### Any log messages given by the failure
>No errors messages given by Android Studio

### Expected/desired behavior
> my expectations were to see the camera screen in order to take a picture

### OS and Version?
> Windows 10
### Versions
> Pro (lastest)

### Mention any other details that might be useful

Practically, once I have ran the sample, I see the application in my android device but when i start it, the application show me a screen all purple and after that like 1-2 seconds, the application crash saying "the application has stopped".
So now I don't know if that's an Android Studio problem or a issue of the code, but i've just copied yours.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by amin-b** [comment]
@AlbertoMocchi please share some logs. it will be hard to guess what the issue is with no logs.

Also, I'm not sure if you've checked other issues, you might be hitting [this](https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/issues/3)

**Comment by AlbertoMocchi** [comment]
Thank for the reply! I can't show you logs because there is no errors, anyway I recorded a video for show you the problem, I'll wait your anwser :)
<div style="width:100%;height:0px;position:relative;padding-bottom:177.778%;"><iframe src="https://streamable.com/s/3m9k4/vxuzrj" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>

**Comment by amin-b** [comment]
@AlbertoMocchi thanks, this sample is not expected to work on emulator as is (because of dependencies on Camera hardware). Would you be able to try on a device?
I'm curious what you'll see in logcat when you test on a physical device.

**Comment by AlbertoMocchi** [comment]
Well, i connected my device, no logs errors appears, but when i start the application from my phone, it stops like in a Android Studio Virtual Device but this time no errors appear on the screen, it just crash. This is the log: 

> Testing started at 20:23 ...
> 
> 01/30 20:23:28: Launching ExampleInstrumentedT...
> $ adb push E:\Download\cognitive-services-android-customvision-sample-master\app\build\outputs\apk\debug\app-debug.apk /data/local/tmp/demo.tensorflow.org.customvision_sample
> $ adb shell pm install -t -r "/data/local/tmp/demo.tensorflow.org.customvision_sample"
> 	pkg: /data/local/tmp/demo.tensorflow.org.customvision_sample
> Success
> 
> 
> No apk changes detected since last installation, skipping installation of E:\Download\cognitive-services-android-customvision-sample-master\app\build\outputs\apk\androidTest\debug\app-debug-androidTest.apk
> $ adb shell am force-stop demo.tensorflow.org.customvision_sample.test
> Running tests
> 
> $ adb shell am instrument -w -r   -e debug false -e class demo.tensorflow.org.customvision_sample.ExampleInstrumentedTest demo.tensorflow.org.customvision_sample.test/android.support.test.runner.AndroidJUnitRunner
> Client not ready yet..
> Started running tests
> Tests ran to completion.
>

**Comment by AlbertoMocchi** [comment]
Oh, something appeared when i stopped the application from my device, this is the Logcat: 

> 01-30 20:29:26.529 18752-18752/demo.tensorflow.org.customvision_sample I/TensorFlowInferenceInterface: TensorFlow native methods already loaded
> 01-30 20:29:26.626 18752-18774/demo.tensorflow.org.customvision_sample I/BufferQueueProducer: [unnamed-18752-0](this:0x55a94cf830,id:0,api:4,p:15692,c:18752) queueBuffer: slot 1 is dropped, handle=0x55a9411920
> 01-30 20:29:26.653 18752-18752/demo.tensorflow.org.customvision_sample I/TensorFlowInferenceInterface: Model load took 81ms, TensorFlow version: 1.3.0
> 01-30 20:29:26.653 18752-18752/demo.tensorflow.org.customvision_sample I/TensorFlowInferenceInterface: Successfully loaded model from 'file:///android_asset/model.pb'
> 01-30 20:29:26.655 18752-18752/demo.tensorflow.org.customvision_sample I/tensorflow: ClassifierActivity: Sensor orientation: 90, Screen orientation: 0
> 01-30 20:29:26.655 18752-18752/demo.tensorflow.org.customvision_sample I/tensorflow: ClassifierActivity: Initializing at size 640x480
> 01-30 20:29:26.657 18752-18752/demo.tensorflow.org.customvision_sample W/tensorflow: ImageUtils: Native library not found, native RGB -> YUV conversion may be unavailable.
> 01-30 20:29:26.658 18752-18752/demo.tensorflow.org.customvision_sample E/art: No implementation found for void demo.tensorflow.org.customvision_sample.env.ImageUtils.convertYUV420SPToARGB8888(byte[], int[], int, int, boolean) (tried Java_demo_tensorflow_org_customvision_1sample_env_ImageUtils_convertYUV420SPToARGB8888 and Java_demo_tensorflow_org_customvision_1sample_env_ImageUtils_convertYUV420SPToARGB8888___3B_3IIIZ)
> 01-30 20:29:26.658 18752-18752/demo.tensorflow.org.customvision_sample D/AndroidRuntime: Shutting down VM
> 01-30 20:29:26.659 18752-18752/demo.tensorflow.org.customvision_sample E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                                          Process: demo.tensorflow.org.customvision_sample, PID: 18752
>                                                                                          java.lang.UnsatisfiedLinkError: No implementation found for void demo.tensorflow.org.customvision_sample.env.ImageUtils.convertYUV420SPToARGB8888(byte[], int[], int, int, boolean) (tried Java_demo_tensorflow_org_customvision_1sample_env_ImageUtils_convertYUV420SPToARGB8888 and Java_demo_tensorflow_org_customvision_1sample_env_ImageUtils_convertYUV420SPToARGB8888___3B_3IIIZ)
>                                                                                              at demo.tensorflow.org.customvision_sample.env.ImageUtils.convertYUV420SPToARGB8888(Native Method)
>                                                                                              at demo.tensorflow.org.customvision_sample.CameraActivity.onPreviewFrame(CameraActivity.java:110)
>                                                                                              at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1260)
>                                                                                              at android.os.Handler.dispatchMessage(Handler.java:111)
>                                                                                              at android.os.Looper.loop(Looper.java:194)
>                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5549)
>                                                                                              at java.lang.reflect.Method.invoke(Native Method)
>                                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
>                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
> 01-30 20:29:26.679 18752-18752/demo.tensorflow.org.customvision_sample I/Process: Sending signal. PID: 18752 SIG: 9
>

**Comment by amin-b** [comment]
Great, this sounds like lack of Camera2 api support on your device.
you can lookup "Camera API lv2" in logcat, if that's showing "false" that's definitely the reason.

at the moment, you can either use another device that supports camera2 api or look at the [previous issue](https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/issues/3) for a possible workaround by modifying TensorFlow's Android sample.

**Comment by AlbertoMocchi** [comment]
Yes, it coul be. When I get home I'll try, but yesterday I tried run the same Project with a Pixel Virtual Device in Android Studio like in the video, and the problem persist so... I don't know!
I'll let you know as soon as possible

**Comment by amin-b** [comment]
take a look at @Florin-Birgu's [workaround](https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/issues/3) about how to make it work using latest TensorFlow Android sample.

**Comment by AlbertoMocchi** [comment]
Ok, i looked at @Florin-Birgu's workaround and after this my application doesn't crash, but this is what I see, is it ok? 
![photo_2018-02-01_15-26-53](https://user-images.githubusercontent.com/28652747/35683491-68c5fbbc-0764-11e8-8368-8db455b06fc6.jpg)
Anyway now I'll try the TensorFlow's Android sample and use Custom Vision's exported model in it.  
I hope this time evrything will be ok!

**Comment by AlbertoMocchi** [comment]
Perfect! It worked! And now the Custom Vision Sample works too.
I have one more question if I can :) 
At the moment the application tells you in real time what think the object is, what I would like is that instead of doing this, the application tells what it think is only after I took a picture, is it possible?
Thank you!

**Comment by amin-b** [comment]
Awesome,
yes, you can modify the code to achieve that, basically you can use any Android boilerplate code to capture an image from Camera. after that you can pass the Bitmap image that you got from Camera apis to [classifyImage](https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/master/app/src/main/java/demo/tensorflow/org/customvision_sample/MSCognitiveServicesClassifier.java#L82) to classify it.
