### ISSUE TITLE
ognitive-services-android-customvision-sample-master\app\build\intermediates\incremental\mergeDebugAndroidTestResources\merged.dir\values-ldltr-v21\values-ldltr-v21.xml

### ISSUE THREAD

**Issue by saturnzxc** [Azure-Samples/cognitive-services-android-customvision-sample#5]
![image](https://user-images.githubusercontent.com/35040122/35610984-7782c930-069e-11e8-937d-e2ba22abdec3.png)

C:\Users\MSI GAMING\Desktop\cognitive-services-android-customvision-sample-master\cognitive-services-android-customvision-sample-master\app\build\intermediates\incremental\mergeDebugAndroidTestResources\merged.dir\values-ldltr-v21\values-ldltr-v21.xml
Error:error: file not found.
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:mergeDebugAndroidTestResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Information:3 errors

Please help me! This is my problem when I open this file to Android studio.

**Comment by amin-b** [comment]
Are you using Android Studio 3 (latest version) + gradle 3?
Could it be because of your path length?
