### ISSUE TITLE
What are the correct mean values for the different project domains?

### ISSUE THREAD

**Issue by daltskin** [Azure-Samples/cognitive-services-android-customvision-sample#6]
[Readme.md](https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/master/README.md) references the following mean values for the different project domains:

Project's Domain | Mean Values (RGB)
-- | --
General (compact) | (123, 117, 104)
Landmark (compact) | (123, 117, 104)
Retail (compact) | (0, 0, 0)

However, within the [sample code](https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/master/app/src/main/java/demo/tensorflow/org/customvision_sample/MSCognitiveServicesClassifier.java) it uses the following values:

    private static final float IMAGE_MEAN_R = 124.f;
    private static final float IMAGE_MEAN_G = 117.f;
    private static final float IMAGE_MEAN_B = 105.f;

What are the correct mean values to use for each project domain?

**Comment by amin-b** [comment]
@daltskin you can use the ones in Readme.
